from pathlib import Path
from html import escape
root=Path(__file__).parent/'docs'
name='RoundTable AI'
nav='<nav aria-label="Main"><a href="/roundtable-ai-site/">'+name+'</a><span><a href="/roundtable-ai-site/support/">Support</a><a href="/roundtable-ai-site/privacy/">Privacy</a><a href="/roundtable-ai-site/terms/">Terms</a></span></nav>'
def page(route,title,body):
 p=root/route/'index.html';p.parent.mkdir(parents=True,exist_ok=True)
 p.write_text('<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>'+escape(title)+' — '+name+'</title><meta name="description" content="'+escape(title)+' for the RoundTable AI macOS app."><link rel="stylesheet" href="/roundtable-ai-site/style.css"></head><body>'+nav+'<main><p class="eyebrow">ROUNDTABLE AI · MACOS</p><h1>'+title+'</h1>'+body+'</main><footer>© 2026 Kunliang Wu · <a href="/roundtable-ai-site/privacy/">Privacy policy</a> · <a href="/roundtable-ai-site/terms/">Terms of use</a></footer></body></html>')
page('support','Support','''<p class="lead">Start with a question. Add context, choose your perspectives, then follow the discussion and decision report.</p>
<h2>Connect your model</h2><p>Open Settings → Models. Add a compatible provider, endpoint, API key and model. Review the AI data-sharing notice and allow the connection before testing or generating. Your provider bills model usage separately from the app purchase.</p>
<h2>A request fails or stalls</h2><p>Check your endpoint, selected model, API key, provider balance and network connection. Review AI permission in Settings → Models if you previously declined or revoked it. Pause a discussion before changing its context; continue when ready. A model provider outage or rate limit can interrupt generation.</p>
<h2>Restore lifetime access</h2><p>Open Settings → Lifetime unlock and choose Restore purchases. Use the Apple Account that made the purchase. The app verifies the purchase with StoreKit. A refunded or revoked purchase no longer grants unlimited discussions.</p>
<h2>Free discussions and history</h2><p>Five completed discussions are free. A discussion counts once when its first report is saved; continuing it does not consume another free discussion. Existing history and Markdown export remain available without buying lifetime access.</p>
<h2>Contact support</h2><p>Email <a href="mailto:wklken@gmail.com">wklken@gmail.com</a> for app support.</p><p>Include your macOS version, app version, what you expected and the error message. Remove API keys, passwords and private conversation content from screenshots or logs.</p>''')
page('privacy','Privacy policy','''<p class="lead">Your discussion history stays on your Mac. AI requests go directly to the model connection you choose, after your permission.</p><p>Last updated: September 12, 2026. This policy describes the RoundTable AI macOS app, provided by Kunliang Wu.</p>
<h2>Data stored on your Mac</h2><p>The app stores conversations, generated reports, expert settings, model connections and preferences locally. It does not provide an app account or cloud synchronization service. API keys are encrypted locally, with the encryption key stored on the same Mac. This does not encrypt your entire conversation history; protect your Mac and backups appropriately.</p>
<h2>Data sent for AI requests</h2><p>When you permit a connection, the app sends the information needed for model discovery and generation directly to that endpoint. This can include your question, background you supply, conversation history, earlier model replies, expert instructions and model settings. The API key is sent as authentication. The provider also receives ordinary connection information such as your IP address. Later speakers can receive earlier discussion content to respond in context.</p><p>The consent screen identifies the connection and endpoint. You choose the provider, including a compatible local endpoint where supported. The developer does not operate a proxy for these requests and does not receive your conversations or keys through an app backend.</p>
<h2>Your provider's processing</h2><p>Providers process requests under their own terms and privacy policies. Retention, training use, account association and processing countries depend on the provider, endpoint and your account settings. The app does not promise zero retention or prevent a provider from keeping data already received. Review your provider's policy before sending personal or confidential information.</p>
<h2>Your choices</h2><p>You can decline AI permission, review it in Settings → Models, or revoke it to prevent future requests. Revocation does not undo completed transfers or recall an in-flight request. You can export reports and delete local conversations using the app. Separately remove exported files and backups you no longer need. Contact the provider for requests about data it retains.</p>
<h2>Purchases</h2><p>Apple processes purchases and payments. The app reads verified StoreKit transaction and entitlement information to unlock or restore features. The developer does not receive your payment-card information through the app. Apple's own privacy policy applies to its services.</p>
<h2>Other network activity</h2><p>Provider icons may be downloaded from GitHub and cached locally. Those requests disclose ordinary network information to the hosting service; they do not include your API keys or discussion text. Opening external links uses your browser. The app contains no advertising or third-party analytics SDK.</p>
<h2>Support and this website</h2><p>If you contact support, the developer receives the message and the contact details you choose to provide, for handling your request. Do not send API keys or passwords. This website has no advertising, analytics scripts or conversation-upload form. Its hosting service processes ordinary network requests to serve the pages. Your language choice is stored in this browser so the website can remember it.</p>
<h2>Contact and updates</h2><p>Email <a href="mailto:wklken@gmail.com">wklken@gmail.com</a> for privacy questions or requests.</p><p>Contact the developer for questions or requests concerning support correspondence. We will update this page when app practices change, with the revision date above.</p>''')
page('terms','Terms of use','''<p class="lead">A tool to support your thinking, using your own model connection.</p><p>Last updated: September 12, 2026. RoundTable AI is provided by Kunliang Wu.</p>
<h2>License</h2><p>The app is licensed under <a href="https://www.apple.com/legal/internet-services/itunes/dev/stdeula/">Apple's Standard End User License Agreement</a>. These product notes explain how the app and purchase work; they do not replace that agreement or limit rights you have under applicable consumer law.</p>
<h2>Lifetime unlock</h2><p>Five completed discussions are free. An optional one-time, non-consumable purchase unlocks unlimited discussions in the app. It is not a recurring subscription. The App Store shows the price and applicable taxes for your region before purchase. Restore the purchase using the same Apple Account. A refund or revocation removes the paid entitlement.</p><p>The unlock does not include model credits, a hosted AI service or a guarantee that a third-party provider will remain available. You supply any necessary API key and pay the provider's charges separately. Your history and Markdown export remain available without the unlock.</p>
<h2>AI output and your decisions</h2><p>Perspectives and moderator reports are generated by AI, not independent human experts. They can contain errors, unsupported assumptions or shared biases. Verify important information and make your own decisions. The app is not a substitute for qualified medical, legal, financial or other professional advice, and is not an emergency service.</p>
<h2>Your content and connections</h2><p>You retain your rights in content you provide. Only submit content you are entitled to use and share with your chosen provider. Follow that provider's terms and applicable law. You are responsible for selecting an appropriate endpoint and protecting your API key.</p>
<h2>Privacy, support and refunds</h2><p>Read our <a href="/roundtable-ai-site/privacy/">privacy policy</a> for data handling and permission controls. See <a href="/roundtable-ai-site/support/">support</a> for troubleshooting. Purchases are processed by Apple; refund requests follow Apple's refund process and applicable consumer rights.</p>''')
(root/'style.css').write_text('''*{box-sizing:border-box}html{font-family:system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;color:#17212b;background:#fff}body{margin:0}a{color:#145fc1;text-underline-offset:.2em}nav{max-width:1080px;margin:auto;padding:30px 32px;display:flex;justify-content:space-between;gap:24px;border-bottom:1px solid #dce3e9}nav>a{font-weight:750;color:#17212b;text-decoration:none;font-size:1.15rem}nav span{display:flex;gap:24px}main{max-width:800px;padding:64px 32px 80px;margin:auto}h1{font-size:clamp(2.2rem,5vw,3.3rem);letter-spacing:-.04em;line-height:1.12;margin:12px 0 24px}h2{font-size:1.25rem;line-height:1.4;margin:36px 0 10px}p{font-size:1rem;line-height:1.8;margin:0 0 16px}.lead{font-size:1.25rem;line-height:1.65;color:#445362;margin-bottom:32px}.eyebrow{font-size:.875rem;font-weight:650;letter-spacing:.08em;color:#145fc1}.links{border-top:1px solid #dce3e9}.links>a{display:block;text-decoration:none;border-bottom:1px solid #dce3e9;padding:20px 0}.links h2{margin:0 0 8px}.links p{color:#445362;margin:0}footer{max-width:1080px;margin:auto;padding:24px 32px;border-top:1px solid #dce3e9;font-size:.875rem;line-height:1.8;color:#52616f}.draft{padding:12px 16px;border-left:3px solid #bd770c;background:#fff5df}a:focus-visible{outline:3px solid #145fc1;outline-offset:5px}@media(max-width:550px){nav{flex-direction:column;padding:24px}main{padding:40px 24px 56px}nav span{gap:22px}}''')
print('Wrote four pages and shared stylesheet')

# Keep the product landing page separate from the legal-page template.
from shutil import copy2
source = Path(__file__).parent
for filename in ['landing.css', 'landing.js']:
 copy2(source/filename, root/filename)
copy2(source/'landing.html', root/'index.html')
(root/'assets').mkdir(exist_ok=True)
copy2(source/'assets'/'pilot-discussion.jpg', root/'assets'/'pilot-discussion.jpg')
(root/'.nojekyll').touch()

copy2(source/'assets'/'app-icon.png', root/'assets'/'app-icon.png')

for filename in ["site.css", "language.js"]:
 copy2(source/filename, root/filename)
from localize import build
build()
